
import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WIN10
 */
public class AdamAsmaca extends javax.swing.JFrame {
    int sayac=0;
    String secilenSehir;
    char [] sifreliSehir;
    String[] sehirler = {"ADANA", "ADIYAMAN", "AFYONKARAHİSAR", "AĞRI", "AMASYA", "ANKARA", "ANTALYA", "ARTVİN",
            "AYDIN", "BALIKESİR", "BİLECİK", "BİNGÖL", "BİTLİS", "BOLU", "BURDUR", "BURSA", "ÇANAKKALE", "ÇANKIRI", "ÇORUM",
            "DENİZLİ", "DİYARBAKIR", "EDİRNE", "ELAZIĞ", "ERZİNCAN", "ERZURUM", "ESKİŞEHİR", "GAZİANTEP", "GİRESUN", "GÜMÜŞHANE",
            "HAKKARİ", "HATAY", "ISPARTA", "MERSİN", "İSTANBUL", "İZMİR", "KARS", "KASTAMONU", "KAYSERİ", "KIRIKKALE", "KIRKLARELİ",
            "KIRŞEHİR", "KOCAELİ", "KONYA", "KÜTAHYA", "MALATYA", "MANİSA", "KAHRAMANMARAŞ", "MARDİN", "MUĞLA", "MUŞ", "NEVŞEHİR",
            "NİĞDE", "ORDU", "RİZE", "SAKARYA", "SAMSUN", "SİİRT", "SİNOP", "SİVAS", "TEKİRDAĞ", "TOKAT", "TRABZON", "TUNCELİ",
            "ŞANLIURFA", "UŞAK", "VAN", "YOZGAT", "ZONGULDAK", "AKSARAY", "BAYBURT", "KARAMAN", "KIRIKKALE", "BATMAN", "ŞIRNAK",
            "BARTIN", "ARDAHAN", "IĞDIR", "YALOVA", "KARABÜK", "KİLİS","OSMANİYE"};
    /**
     * Creates new form AdamAsmaca
     */
    public AdamAsmaca() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        basla();
    }
    
    public String sehirSec(){
        int rastgeleSayi=(int)(Math.random()*sehirler.length);
        secilenSehir = sehirler[rastgeleSayi];
        return secilenSehir;
    }
    public char[]sehriSifrele(int uzunluk){
        char [] sifreliSehirOlustur=new char[uzunluk];
        for (int i = 0; i < uzunluk; i++) {
            sifreliSehirOlustur[i]='_';
            
        }
        return sifreliSehirOlustur;
    }
    public char [] sehriAc(char[]sifre,char karakter,String seciliSehir){
        for (int i = 0; i < seciliSehir.length(); i++) {
            if (seciliSehir.charAt(i)==karakter) {
                sifre[i]=karakter;
                
            }
            
        }
        return sifre;
    }
    public boolean sehrinTamamiAcildiMi(char[]sifreliGelenSehir){
        for (int i = 0; i < sifreliGelenSehir.length; i++) {
            if (sifreliGelenSehir[i]=='_') {
                return false;
                
            }
            
        }
        return true;
    }
    DefaultListModel model=new DefaultListModel();
    public void yenidenBaslat(){
        sayac=0;
        secilenSehir=sehirSec();
        sifreliSehir=sehriSifrele(secilenSehir.length());
        
        String gizliSehir="";
        for (int i = 0; i < sifreliSehir.length; i++) {
            gizliSehir+="_";
            
        }
        lblSifreliSehir.setText(gizliSehir);
        
        ImageIcon img=new ImageIcon("D:\\netbeans\\18subat\\src\\image\\0.jpg"); 
        lblAdamResmi.setIcon(img);
        
        txtGirilenSehir.setText("");
        lstCikanHarf.setModel(model);
        model.clear();
        
        kalanDenemeHakki();
    }
    public void kalanDenemeHakki(){
        lblSayac.setText(""+(10-sayac));
    }
    public boolean tahminYanlisMi(char girilenKarakter){
        boolean tahmin=true;
        sifreliSehir=sehriAc(sifreliSehir,girilenKarakter,secilenSehir);
                for(int i=0;i<sifreliSehir.length;i++){
                    if ((sifreliSehir[i]==girilenKarakter)) {
                        tahmin=false;
                        break;
                    }
                    
                } 
                return tahmin;
    }
    public void basla(){
        secilenSehir=sehirSec();
        sifreliSehir=sehriSifrele(secilenSehir.length());
        
        String gizliSehir="";
        for (int i = 0; i < sifreliSehir.length; i++) {
            gizliSehir+="_";
            
        }
        lblSifreliSehir.setText(gizliSehir);
        
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdamResmi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSifreliSehir = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGirilenSehir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCikanHarf = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        lblSayac = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdamResmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/0.jpg"))); // NOI18N
        lblAdamResmi.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(153, 51, 0));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("ADAM ASMACA");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSifreliSehir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSifreliSehir.setForeground(new java.awt.Color(204, 102, 0));
        lblSifreliSehir.setText("jLabel3");
        lblSifreliSehir.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("harf alın :");

        txtGirilenSehir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGirilenSehirActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("AL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("çıkmış harfler :");

        jScrollPane1.setViewportView(lstCikanHarf);

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setText("kalan hakkınız :");

        lblSayac.setBackground(new java.awt.Color(255, 255, 255));
        lblSayac.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        lblSayac.setForeground(new java.awt.Color(0, 0, 0));
        lblSayac.setText("10");

        jButton2.setBackground(new java.awt.Color(204, 102, 0));
        jButton2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("RESART");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAdamResmi, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSayac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGirilenSehir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSifreliSehir)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(266, 266, 266))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSifreliSehir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGirilenSehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSayac)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblAdamResmi, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String girilenHarf=txtGirilenSehir.getText().toUpperCase();
        if (girilenHarf.length()==1) {
            char karakter=girilenHarf.charAt(0);
            sifreliSehir=sehriAc(sifreliSehir,karakter,secilenSehir);
            String sifreliSehirYazdir = "";
            for (int i = 0; i < sifreliSehir.length; i++) {
                sifreliSehirYazdir+=sifreliSehir[i];
                
            }
            lblSifreliSehir.setText(sifreliSehirYazdir);
            
            if (sehrinTamamiAcildiMi(sifreliSehir)) {
                JOptionPane.showMessageDialog(rootPane, "tebrikler kazandiniz☻");
                yenidenBaslat();
                return;
                
            }
            if (tahminYanlisMi(karakter)) {
                sayac++;
                kalanDenemeHakki();
                
                ImageIcon img=new ImageIcon("D:\\netbeans\\18subat\\src\\image\\"+sayac+".jpg"); 
                lblAdamResmi.setIcon(img);
                
                lstCikanHarf.setModel(model);
                model.addElement(karakter);
                lstCikanHarf.setPreferredSize(new Dimension(225,110));
                
            }
            if (sayac==10) {
                JOptionPane.showMessageDialog(rootPane, "uzgunuz kaybettiniz : sehir -> '"+secilenSehir+"'");
                yenidenBaslat();
                return;
            }
        }
        else{
           JOptionPane.showMessageDialog(null, "lütfen tek karakter harf giriniz");
        }
        txtGirilenSehir.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        yenidenBaslat();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtGirilenSehirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGirilenSehirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGirilenSehirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdamAsmaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdamResmi;
    private javax.swing.JLabel lblSayac;
    private javax.swing.JLabel lblSifreliSehir;
    private javax.swing.JList<String> lstCikanHarf;
    private javax.swing.JTextField txtGirilenSehir;
    // End of variables declaration//GEN-END:variables
}
